services:
  ###> doctrine/doctrine-bundle ###
  app:
    image: thecodingmachine/php:8.4-v5-apache-node24
    ports:
      - "8080:80"
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 0
      PHP_EXTENSION_INTL: 1
      PHP_INI_UPLOAD_MAX_FILESIZE: 30M
      PHP_INI_POST_MAX_SIZE: 50M
    volumes:
      - "./:/var/www/html"
      - "~/.composer:/tmp/docker/.composer"
      - "~/.config/composer:/var/www/.config/composer"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-firecount}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p@ssword}
      POSTGRES_USER: ${POSTGRES_USER:-firecount_user}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
